package ext

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// mergeHeadersHelperJS is emitted once per generated module — only
// operations with a request body need it, but defining it
// unconditionally keeps renderFunctionJS simple and the cost is a few
// bytes of unused-but-harmless JS when no operation has a body.
const mergeHeadersHelperJS = `function _mergeHeaders(a, b) {
  var out = {};
  for (var k in a) { out[k] = a[k]; }
  for (var k in b) { out[k] = b[k]; }
  return out;
}
`

// renderSkill renders the full require()-able module source and the
// skillGet() docs text for ops, in the order given (collectOperations
// already sorted it deterministically).
func renderSkill(baseURL string, headers map[string]string, ops []operation) (moduleJS, docs string) {
	baseURL = strings.TrimSuffix(baseURL, "/")
	if headers == nil {
		headers = map[string]string{}
	}
	headerJSON, err := json.Marshal(headers)
	if err != nil {
		// map[string]string cannot fail to marshal.
		headerJSON = []byte("{}")
	}

	var js strings.Builder
	js.WriteString("// Generated by ext.OpenAPIPack — do not edit by hand.\n")
	fmt.Fprintf(&js, "var BASE_URL = %q;\n", baseURL)
	fmt.Fprintf(&js, "var HEADERS = %s;\n", headerJSON)
	js.WriteString(mergeHeadersHelperJS)
	js.WriteString("\n")

	var doc strings.Builder
	fmt.Fprintf(&doc, "REST API — %d operation(s), base URL %s.\n", len(ops), baseURL)
	doc.WriteString("Every function takes one params object and returns {status, body, headers} — same shape as fetch()/require('http') — body is a raw string, JSON.parse it if the response is JSON.\n\n")

	for _, op := range ops {
		js.WriteString(renderFunctionJS(op))
		js.WriteString("\n")
		doc.WriteString(renderFunctionDoc(op))
		doc.WriteString("\n")
	}

	return js.String(), strings.TrimRight(doc.String(), "\n")
}

func renderFunctionJS(op operation) string {
	var b strings.Builder
	fmt.Fprintf(&b, "exports.%s = function(params) {\n", op.funcName)
	b.WriteString("  params = params || {};\n")
	fmt.Fprintf(&b, "  var url = %s;\n", pathExprJS(op.path))

	if len(op.queryParams) > 0 {
		b.WriteString("  var qs = [];\n")
		for _, q := range op.queryParams {
			fmt.Fprintf(&b, "  if (params.%s !== undefined) qs.push(%s + \"=\" + encodeURIComponent(String(params.%s)));\n",
				q.name, strconv.Quote(q.name), q.name)
		}
		b.WriteString("  if (qs.length > 0) url += \"?\" + qs.join(\"&\");\n")
	}

	headersExpr := "HEADERS"
	bodyArg := ""
	if op.hasBody {
		b.WriteString("  var body = \"\";\n")
		b.WriteString("  var reqHeaders = HEADERS;\n")
		b.WriteString("  if (params.body !== undefined) {\n")
		b.WriteString("    body = JSON.stringify(params.body);\n")
		b.WriteString("    reqHeaders = _mergeHeaders(HEADERS, {\"Content-Type\": \"application/json\"});\n")
		b.WriteString("  }\n")
		headersExpr = "reqHeaders"
		bodyArg = "body: body, "
	}

	fmt.Fprintf(&b, "  return _http(url, {method: %q, %sheaders: %s});\n", op.method, bodyArg, headersExpr)
	b.WriteString("};\n")
	return b.String()
}

func renderFunctionDoc(op operation) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s(params) — %s %s\n", op.funcName, op.method, op.path)
	if op.summary != "" {
		fmt.Fprintf(&b, "  %s\n", op.summary)
	}
	for _, name := range op.pathParams {
		fmt.Fprintf(&b, "  params.%s (path, required)\n", name)
	}
	for _, q := range op.queryParams {
		req := "optional"
		if q.required {
			req = "required"
		}
		fmt.Fprintf(&b, "  params.%s (query, %s, %s)\n", q.name, req, q.typ)
	}
	if op.hasBody {
		req := "optional"
		if op.bodyRequired {
			req = "required"
		}
		fmt.Fprintf(&b, "  params.body (%s) — request body, JSON-serialized\n", req)
	}
	return b.String()
}

var pathParamRe = regexp.MustCompile(`\{([^}]+)\}`)

// pathExprJS renders a JS expression that builds the request URL for
// path (an OpenAPI path template like "/pets/{petId}/photos") by
// string-concatenating BASE_URL, the template's literal segments, and
// encodeURIComponent(String(params.<name>)) for each {param}.
func pathExprJS(path string) string {
	var b strings.Builder
	b.WriteString("BASE_URL")
	last := 0
	for _, m := range pathParamRe.FindAllStringSubmatchIndex(path, -1) {
		if lit := path[last:m[0]]; lit != "" {
			fmt.Fprintf(&b, " + %q", lit)
		}
		name := sanitizeIdent(path[m[2]:m[3]])
		fmt.Fprintf(&b, " + encodeURIComponent(String(params.%s))", name)
		last = m[1]
	}
	if last < len(path) {
		fmt.Fprintf(&b, " + %q", path[last:])
	}
	return b.String()
}
